/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ForecastService } from "../forecast.service";
import { ForecastCreateInput } from "./ForecastCreateInput";
import { Forecast } from "./Forecast";
import { ForecastFindManyArgs } from "./ForecastFindManyArgs";
import { ForecastWhereUniqueInput } from "./ForecastWhereUniqueInput";
import { ForecastUpdateInput } from "./ForecastUpdateInput";

export class ForecastControllerBase {
  constructor(protected readonly service: ForecastService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Forecast })
  async createForecast(
    @common.Body() data: ForecastCreateInput
  ): Promise<Forecast> {
    return await this.service.createForecast({
      data: {
        ...data,

        city: data.city
          ? {
              connect: data.city,
            }
          : undefined,
      },
      select: {
        city: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        forecastTime: true,
        humidity: true,
        id: true,
        temperature: true,
        updatedAt: true,
        windSpeed: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Forecast] })
  @ApiNestedQuery(ForecastFindManyArgs)
  async forecasts(@common.Req() request: Request): Promise<Forecast[]> {
    const args = plainToClass(ForecastFindManyArgs, request.query);
    return this.service.forecasts({
      ...args,
      select: {
        city: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        forecastTime: true,
        humidity: true,
        id: true,
        temperature: true,
        updatedAt: true,
        windSpeed: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Forecast })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async forecast(
    @common.Param() params: ForecastWhereUniqueInput
  ): Promise<Forecast | null> {
    const result = await this.service.forecast({
      where: params,
      select: {
        city: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        forecastTime: true,
        humidity: true,
        id: true,
        temperature: true,
        updatedAt: true,
        windSpeed: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Forecast })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateForecast(
    @common.Param() params: ForecastWhereUniqueInput,
    @common.Body() data: ForecastUpdateInput
  ): Promise<Forecast | null> {
    try {
      return await this.service.updateForecast({
        where: params,
        data: {
          ...data,

          city: data.city
            ? {
                connect: data.city,
              }
            : undefined,
        },
        select: {
          city: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          forecastTime: true,
          humidity: true,
          id: true,
          temperature: true,
          updatedAt: true,
          windSpeed: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Forecast })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteForecast(
    @common.Param() params: ForecastWhereUniqueInput
  ): Promise<Forecast | null> {
    try {
      return await this.service.deleteForecast({
        where: params,
        select: {
          city: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          forecastTime: true,
          humidity: true,
          id: true,
          temperature: true,
          updatedAt: true,
          windSpeed: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
